/*
 * CSE 29 Buffer Overflow Game - Level 3: "NOP Sled → Root Shell"
 *
 * Do not edit this file!
 *
 * Goal: overwrite the saved return address, land in a NOP sled (\x90),
 * slide into the provided shellcode (shellcode.py), and get a root shell.
 *
 * Why a sled? Your landing address in the buffer can be slightly wrong;
 * NOPs give you a runway so you still reach the shellcode.
 */

#include <stdio.h>
#include <stdlib.h>

#define COLOR_GREEN_BOLD   "\033[1;32m"
#define COLOR_MAGENTA_BOLD "\033[1;35m"
#define COLOR_CYAN         "\033[0;36m"
#define COLOR_DIM          "\033[2m"
#define COLOR_RESET        "\033[0m"

static void banner(void) {
    printf(COLOR_GREEN_BOLD
           "   ____ ____  _____   ____   ___    _   _    _    ____ _  __\n"
           "  / ___/ ___|| ____| |___ \\ / _ \\  | | | |  / \\  / ___| |/ /\n"
           " | |   \\___ \\|  _|     __) | (_) | | |_| | / _ \\| |   | ' / \n"
           " | |___ ___) | |___   / __/ \\__, | |  _  |/ ___ \\ |___| . \\ \n"
           "  \\____|____/|_____| |_____|  /_/  |_| |_/_/   \\_\\____|_|\\_\\\n"
           COLOR_RESET);
    printf(COLOR_MAGENTA_BOLD
           "        [ CSE 29 :: LEVEL 3 :: NOP SLED → ROOT SHELL ]\n\n"
           COLOR_RESET);
    printf(COLOR_CYAN
           "  Overwrite the return address. Aim into a NOP runway (\\x90),\n"
           "  slide into shellcode.py (setuid + /bin/sh), and get a root shell.\n"
           "  Try two different landings in the sled — both should work.\n"
           COLOR_RESET);
    printf(COLOR_DIM
           "  ---------------------------------------------------------\n"
           COLOR_RESET);
}

void vulnerable(void) {
    char buffer[128];

    printf(COLOR_DIM "  [leak] buffer @ %p\n" COLOR_RESET, (void *)buffer);
    gets(buffer); /* intentionally unsafe */
}

int main(void) {
    banner();
    printf(COLOR_DIM "  Logged in as : student (not root yet)\n" COLOR_RESET);
    vulnerable();
    printf(COLOR_DIM "\n  access denied. return address was not hijacked.\n"
           COLOR_RESET);
    return 0;
}
