/*
 * CSE 29 Buffer Overflow Game - Level 3: "NOP Sled → Root Shell"
 *
 * Do not edit this file!
 *
 * Goal: overwrite the saved return address, land in a NOP sled (\x90),
 * slide into the provided shellcode (shellcode.py), and get a root shell.
 *
 * Why a sled? Your landing address in the buffer can be slightly wrong;
 * NOPs give you a runway so you still reach the shellcode.
 */

#include <stdio.h>
#include <stdlib.h>

#define COLOR_DIM          "\033[2m"
#define COLOR_RESET        "\033[0m"

void vulnerable(void) {
    char buffer[128];

    printf(COLOR_DIM "  [leak] buffer @ %p\n" COLOR_RESET, (void *)buffer);
    gets(buffer); /* intentionally unsafe */
}

int main(void) {
    printf(COLOR_DIM "  Logged in as : student (not root yet)\n" COLOR_RESET);
    vulnerable();
    printf(COLOR_DIM "\n  access denied. return address was not hijacked.\n"
           COLOR_RESET);
    return 0;
}
