/*
 * CSE 29 Buffer Overflow Game - Level 3: "Root Shell"
 *
 * Do not edit this file!
 *
 * Goal: overwrite the saved return address so execution jumps to
 * root_shell(), which drops you into /bin/sh.
 *
 * No shellcode and no executable stack required — this is return-to-function
 * (ret2win style). In the course Docker image you are already root, so the
 * shell is a root shell. On a hardened course server this binary would be
 * installed setuid-root carefully; here the lesson is control-flow hijack.
 */

#include <stdio.h>
#include <stdlib.h>

#define COLOR_GREEN_BOLD   "\033[1;32m"
#define COLOR_MAGENTA_BOLD "\033[1;35m"
#define COLOR_CYAN         "\033[0;36m"
#define COLOR_DIM          "\033[2m"
#define COLOR_RESET        "\033[0m"

void root_shell(void) {
    printf(COLOR_GREEN_BOLD
           "\n  *** ACCESS GRANTED :: SPAWNING ROOT SHELL ***\n"
           "  *** LEVEL 3 CLEARED ***\n" COLOR_RESET);
    fflush(stdout);
    system("/bin/sh");
    exit(0);
}

static void banner(void) {
    printf(COLOR_GREEN_BOLD
           "   ____ ____  _____   ____   ___    _   _    _    ____ _  __\n"
           "  / ___/ ___|| ____| |___ \\ / _ \\  | | | |  / \\  / ___| |/ /\n"
           " | |   \\___ \\|  _|     __) | (_) | | |_| | / _ \\| |   | ' / \n"
           " | |___ ___) | |___   / __/ \\__, | |  _  |/ ___ \\ |___| . \\ \n"
           "  \\____|____/|_____| |_____|  /_/  |_| |_/_/   \\_\\____|_|\\_\\\n"
           COLOR_RESET);
    printf(COLOR_MAGENTA_BOLD
           "        [ CSE 29 :: LEVEL 3 :: ROOT SHELL ]\n\n" COLOR_RESET);
    printf(COLOR_CYAN
           "  No shellcode this time. Overwrite the saved return address so\n"
           "  the CPU jumps straight into root_shell() and drops a shell.\n"
           COLOR_RESET);
    printf(COLOR_DIM
           "  ---------------------------------------------------------\n"
           COLOR_RESET);
}

void vulnerable(void) {
    char buffer[64];

    printf(COLOR_MAGENTA_BOLD "  root@cse29:~# " COLOR_RESET
           "enter exploit payload: ");
    fflush(stdout);
    gets(buffer); /* intentionally unsafe */
}

int main(void) {
    banner();
    vulnerable();
    printf(COLOR_DIM "\n  access denied. you did not reach root_shell().\n"
           COLOR_RESET);
    return 0;
}
