/*
 * CSE 29 Buffer Overflow Game - Level 1: "Grade Override"
 *
 * Do not edit this file!
 *
 */

#include <stdio.h>
#define COLOR_GREEN_BOLD   "\033[1;32m"
#define COLOR_MAGENTA_BOLD "\033[1;35m"
#define COLOR_DIM          "\033[2m"
#define COLOR_RESET        "\033[0m"

typedef struct {
    char name[16];
    char grade[4];
} student_cse_29;

int main(void) {
    student_cse_29 student;

    student.grade[0] = 'D';
    student.grade[1] = '\0';

    printf("  grade  : %s\n", student.grade);
    printf(COLOR_MAGENTA_BOLD "  root@cse29:~# " COLOR_RESET "enter your ucsd email without the @: ");
    fflush(stdout);
    gets(student.name); /* depricated function */

    printf("\n  user   : %s\n", student.name);
    printf("  grade  : %s\n", student.grade);

    if (student.grade[0] == 'A' && student.grade[1] == '+') {
        printf(COLOR_GREEN_BOLD "\n  *** ACCESS GRANTED :: GRADE OVERRIDE COMPLETE ***\n" COLOR_RESET);
        printf(COLOR_GREEN_BOLD "  *** LEVEL 1 CLEARED ***\n" COLOR_RESET);
    } else {
        printf(COLOR_DIM "\n  Access Denied. grade still '%s'. keep trying, hacker.\n" COLOR_RESET,
               student.grade);
    }
    return 0;
}
