/*
 * CSE 29 Buffer Overflow Game - Level 2: "NOP Sled"
 *
 * Do not edit this file!
 *
 * Goal: overflow the stack buffer, overwrite the saved return address,
 * and redirect execution into a NOP sled (\x90) that slides into shellcode.
 * The shellcode should call win().
 *
 * The program prints the buffer address once (a deliberate "leak") so you
 * can build a payload even when live GDB is unavailable.
 */

#include <stdio.h>
#include <stdlib.h>

#define COLOR_GREEN_BOLD   "\033[1;32m"
#define COLOR_MAGENTA_BOLD "\033[1;35m"
#define COLOR_CYAN         "\033[0;36m"
#define COLOR_DIM          "\033[2m"
#define COLOR_RESET        "\033[0m"

void win(void) {
    printf(COLOR_GREEN_BOLD
           "\n  *** NOP SLED LANDED :: SHELLCODE REACHED WIN() ***\n"
           "  *** LEVEL 2 CLEARED ***\n" COLOR_RESET);
    exit(0);
}

static void banner(void) {
    printf(COLOR_GREEN_BOLD
           "   ____ ____  _____   ____   ___    _   _    _    ____ _  __\n"
           "  / ___/ ___|| ____| |___ \\ / _ \\  | | | |  / \\  / ___| |/ /\n"
           " | |   \\___ \\|  _|     __) | (_) | | |_| | / _ \\| |   | ' / \n"
           " | |___ ___) | |___   / __/ \\__, | |  _  |/ ___ \\ |___| . \\ \n"
           "  \\____|____/|_____| |_____|  /_/  |_| |_/_/   \\_\\____|_|\\_\\\n"
           COLOR_RESET);
    printf(COLOR_MAGENTA_BOLD
           "        [ CSE 29 :: LEVEL 2 :: NOP SLED ]\n\n" COLOR_RESET);
    printf(COLOR_CYAN
           "  Overflow the stack buffer. Land in a runway of NOPs (\\x90),\n"
           "  slide into shellcode, and call win().\n" COLOR_RESET);
    printf(COLOR_DIM
           "  ---------------------------------------------------------\n"
           COLOR_RESET);
}

void vulnerable(void) {
    char buffer[128];

    /* Deliberate address leak so students can aim the return address
     * at their NOP sled (also useful before they are fluent in GDB). */
    printf(COLOR_DIM "  [leak] buffer @ %p\n" COLOR_RESET, (void *)buffer);
    printf(COLOR_MAGENTA_BOLD "  root@cse29:~# " COLOR_RESET
           "enter exploit payload: ");
    fflush(stdout);
    gets(buffer); /* intentionally unsafe */
}

int main(void) {
    banner();
    vulnerable();
    printf(COLOR_DIM "\n  access denied. return address was not hijacked.\n"
           COLOR_RESET);
    return 0;
}
