/*
 * CSE 29 Buffer Overflow Game - Level 2: "Role Upgrade"
 *
 * Do not edit this file!
 *
 * Goal: overwrite the saved return address so execution jumps to
 * professor_mode() instead of returning to main. That is a simple control-flow hijack.
 * You start as "student". A successful attack prints "professor".
 */

#include <stdio.h>
#include <stdlib.h>

#define COLOR_GREEN_BOLD   "\033[1;32m"
#define COLOR_DIM          "\033[2m"
#define COLOR_RESET        "\033[0m"

void professor_mode(void) {
    printf(COLOR_GREEN_BOLD
           "\n  Logged in as : professor\n"
           "  *** ROLE ELEVATED :: CONTROL FLOW HIJACKED ***\n"
           "  *** LEVEL 2 CLEARED ***\n" COLOR_RESET);
    exit(0);
}

void vulnerable(void) {
    char buffer[64];

    printf(COLOR_DIM "  Logged in as : student\n" COLOR_RESET);
    printf(COLOR_DIM "  [hint] professor_mode @ %p\n" COLOR_RESET,
           (void *)professor_mode);
    gets(buffer); /* intentionally unsafe */
    printf(COLOR_DIM "\n  still 'student'. return address was not hijacked.\n"
           COLOR_RESET);
}

int main(void) {
    vulnerable();
    return 0;
}
