/*
 * CSE 29 Buffer Overflow Game - Level 2: "Role Upgrade"
 *
 * Do not edit this file!
 *
 * Goal: overwrite the saved return address so execution jumps to
 * professor_mode() instead of returning to main. That is a simple
 * control-flow hijack (ret2win) — exact address, no NOP sled, no shellcode.
 *
 * You start as "student". A successful attack prints "professor".
 */

#include <stdio.h>
#include <stdlib.h>

#define COLOR_GREEN_BOLD   "\033[1;32m"
#define COLOR_MAGENTA_BOLD "\033[1;35m"
#define COLOR_CYAN         "\033[0;36m"
#define COLOR_DIM          "\033[2m"
#define COLOR_RESET        "\033[0m"

void professor_mode(void) {
    printf(COLOR_GREEN_BOLD
           "\n  Logged in as : Professor Gerald Soosairaj\n"
           "  *** ROLE ELEVATED :: CONTROL FLOW HIJACKED ***\n"
           "  *** LEVEL 2 CLEARED ***\n" COLOR_RESET);
    exit(0);
}

static void banner(void) {
    printf(COLOR_GREEN_BOLD
           "   ____ ____  _____   ____   ___    _   _    _    ____ _  __\n"
           "  / ___/ ___|| ____| |___ \\ / _ \\  | | | |  / \\  / ___| |/ /\n"
           " | |   \\___ \\|  _|     __) | (_) | | |_| | / _ \\| |   | ' / \n"
           " | |___ ___) | |___   / __/ \\__, | |  _  |/ ___ \\ |___| . \\ \n"
           "  \\____|____/|_____| |_____|  /_/  |_| |_/_/   \\_\\____|_|\\_\\\n"
           COLOR_RESET);
    printf(COLOR_MAGENTA_BOLD
           "        [ CSE 29 :: LEVEL 2 :: ROLE UPGRADE ]\n\n" COLOR_RESET);
    printf(COLOR_CYAN
           "  You are logged in as 'student'. Overwrite the saved return\n"
           "  address so the program jumps to professor_mode() and prints\n"
           "  'professor' instead. Exact address — no NOP sled needed.\n" COLOR_RESET);
    printf(COLOR_DIM
           "  ---------------------------------------------------------\n"
           COLOR_RESET);
}

void vulnerable(void) {
    char buffer[64];

    printf(COLOR_DIM "  Logged in as : student\n" COLOR_RESET);
    printf(COLOR_DIM "  [hint] professor_mode @ %p\n" COLOR_RESET,
           (void *)professor_mode);
    printf(COLOR_MAGENTA_BOLD "  root@cse29:~# " COLOR_RESET
           "enter exploit payload: ");
    fflush(stdout);
    gets(buffer); /* intentionally unsafe */
}

int main(void) {
    banner();
    vulnerable();
    printf(COLOR_DIM "\n  still 'student'. return address was not hijacked.\n"
           COLOR_RESET);
    return 0;
}
